### ISSUE TITLE
md-tooltip

### ISSUE THREAD

**Issue by mbx2015** [ONE-LOGIC/md-color-menu#5]
You should remove the md-tooltip tag in the template of the directive, it make the app so slowly.

**Comment by mathiasmoeller** [comment]
Yes we know. This is a bug introduced by angular-material. `md-menu` does not work together with `md-tooltip` anymore. I created an issue on their GitHub page:
https://github.com/angular/material/issues/6662

Unfortunately they moved it into their backlog. We will fix the problem ASAP.

Thanks for creating the issue!

**Comment by mbx2015** [comment]
Thanks !!

**Comment by mathiasmoeller** [comment]
@mbx2015 tooltips are now disabled by default. You can enable them with the flag `show-tooltips`

**Comment by mbx2015** [comment]
Appreciating your interaction, thanks.
